### ISSUE TITLE
Apology required?

### ISSUE THREAD

**Issue by randycasburn** [Abhi-sigma/Abhi-sigma.github.io#1]
I hope you didn't pull your post off the JavaScript group on LinkedIn because of me. I truly was enjoying providing some answers to your questions and providing a demo. It was a welcome distraction from what I was working on. 

So if I offended you in some way I would like to apologize. Wishing you all the best,

Randy Casburn

**Comment by Abhi-sigma** [comment]
No Sir,I havent pulled off anything.I was flattered to have any kind of response from senior developer like you.I will check what happened.
